export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT"; // Lấy tất cả sản phẩm
export const TOGGLE_AUTH = "TOGGLE_AUTH"; // Bật/tắt trạng thái xác thực
export const GET_ALL_NXB = "GET_ALL_NXB"; // Lấy tất cả nhà xuất bản
export const GET_ALL_POST = "GET_ALL_POST"; // Lấy tất cả bài viết
export const GET_PRODUCT_BY_PAGE = "GET_PRODUCT_BY_PAGE"; // Lấy sản phẩm theo trang
export const IS_LOADING_BOOKSTORE = "IS_LOADING_BOOKSTORE"; // Thiết lập trạng thái loading cho cửa hàng sách
export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT"; // Lấy thông tin chi tiết một sản phẩm
export const IS_LOADING_DETAIL_P = "IS_LOADING_DETAIL_P"; // Thiết lập trạng thái loading cho chi tiết sản phẩm
export const ADD_REVIEW_PRODUCT = "ADD_REVIEW_PRODUCT"; // Thêm đánh giá cho sản phẩm
export const SET_USER = "SET_USER"; // Thiết lập thông tin người dùng
export const IS_LOADING_ALL = 'IS_LOADING_ALL'; // Thiết lập trạng thái loading cho tất cả sản phẩm
export const GET_ONE_POST = 'GET_ONE_POST'; // Lấy thông tin chi tiết một bài viết
export const ADD_CMT_POST = "ADD_CMT_POST"; // Thêm bình luận cho bài viết
export const GET_COMMENT = "GET_COMMENT"; // Lấy thông tin bình luận
export const REPLY_COMMENT = "REPLY_COMMENT"; // Trả lời bình luận
export const IS_LOADING_CMT = "IS_LOADING_CMT"; // Thiết lập trạng thái loading cho bình luận
export const GET_ALL_TYPE_PRODUCT = "GET_ALL_TYPE_PRODUCT"; // Lấy tất cả loại sản phẩm
export const GET_POST_BY_PAGE = "GET_POST_BY_PAGE"; // Lấy bài viết theo trang
export const IS_LOADING_DETAIL_B = "IS_LOADING_DETAIL_B"; // Thiết lập trạng thái loading cho chi tiết bài viết
export const GET_PRODUCT_SEARCH_FIELD = "GET_PRODUCT_SEARCH_FIELD"; // Tìm kiếm sản phẩm theo trường
export const GET_PRODUCT_FILTER_PRICE = "GET_PRODUCT_FILTER_PRICE"; // Lọc sản phẩm theo giá
export const GET_REVIEW = "GET_REVIEW"; // Lấy thông tin đánh giá sản phẩm
export const TOGGLE_CART = "TOGGLE_CART"; // Bật/tắt giỏ hàng
export const GET_CART = 'GET_CART'; // Lấy thông tin giỏ hàng
export const ADD_CART = "ADD_CART"; // Thêm sản phẩm vào giỏ hàng
export const IS_LOADING_CART = 'IS_LOADING_CART'; // Thiết lập trạng thái loading cho giỏ hàng
export const DELETE_PRODUCT_IN_CART = 'DELETE_PRODUCT_IN_CART'; // Xóa sản phẩm khỏi giỏ hàng
export const AMOUNT_CART = "AMOUNT_CART"; // Thiết lập số lượng sản phẩm trong giỏ hàng
export const RESET_CART = "RESET_CART"; // Reset giỏ hàng
export const UPDATE_ONE_CART = "UPDATE_ONE_CART"; // Cập nhật một sản phẩm trong giỏ hàng
export const IS_LOADING_PC = "IS_LOADING_PC"; // Thiết lập trạng thái loading cho PC
export const SET_SUB_TOTAL_CART = "SET_SUB_TOTAL_CART"; // Thiết lập tổng tiền giỏ hàng
export const GET_PRODUCT_RELATED = "GET_PRODUCT_RELATED"; // Lấy sản phẩm liên quan
export const GET_PRODUCT_ALSO_LIKE = "GET_PRODUCT_ALSO_LIKE"; // Lấy sản phẩm tương tự
export const IS_LOADING_AUTH = "IS_LOADING_AUTH"; // Thiết lập trạng thái loading cho quá trình xác thực
export const PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"; // Thiết lập trạng thái không tìm thấy sản phẩm
export const DELETE_CMT = "DELETE_CMT"; // Xóa bình luận
export const ON_RESET_POSTS = "ON_RESET_POSTS"; // Reset thông tin bài viết